# Generated by Django 4.0.4 on 2022-05-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orderto_productmark_productnumber_producttype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderto',
            options={'verbose_name': 'Тип ордера', 'verbose_name_plural': 'Типы ордера'},
        ),
        migrations.AlterModelOptions(
            name='productmark',
            options={'verbose_name': 'Марка продукта', 'verbose_name_plural': 'марки продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productnumber',
            options={'verbose_name': 'Номер продукта', 'verbose_name_plural': 'Номера продуктов'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Тип продукта', 'verbose_name_plural': 'Типы продуктов'},
        ),
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Продукты'),
        ),
    ]
