# Generated by Django 4.0.4 on 2022-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_much',
            field=models.FloatField(null=True, verbose_name='Кол-во (млн. тон)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mark',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
    ]
