# Generated by Django 4.0.4 on 2022-05-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_product_much_profile_mark_alter_product_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_much',
            field=models.FloatField(default=0, verbose_name='Кол-во (млн. тон)'),
            preserve_default=False,
        ),
    ]
