# Generated by Django 4.0.4 on 2022-06-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_rating_options_rating_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='iconName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id иконки'),
        ),
    ]
