# Generated by Django 4.0.4 on 2022-06-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_producttype_iconname'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='className',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс иконки'),
        ),
    ]
