# Generated by Django 4.0.4 on 2022-06-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_producttype_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='iconName',
        ),
    ]
