# Generated by Django 4.0.4 on 2022-06-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile_adres_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adres',
            field=models.TextField(default='-', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='-', max_length=50, verbose_name='Телефон'),
        ),
    ]
